---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      hostNetwork: false
      hostPort:
        enabled: false
      ingressClassResource:
        default: true
      kind: DaemonSet
      service:
        enabled: true
        annotations:
          cloudprovider.harvesterhci.io/ipam: dhcp
        externalTrafficPolicy: "Local"
        type: LoadBalancer
